services:
  duckdns:
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - SUBDOMAINS=$DUCKDNS_SUBDOMAIN
      - TOKEN=$DUCKDNS_TOKEN
    restart: unless-stopped
    image: 'ghcr.io/linuxserver/duckdns:latest'

  nginxproxymanager:
    container_name: nginxproxymanager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/danieldbird/Dockers/nginxproxymanager/data:/data
      - /home/danieldbird/Dockers/nginxproxymanager/etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    image: 'jc21/nginx-proxy-manager:latest'

  uptime-kuma:
    container_name: uptime-kuma
    ports:
      - '3001:3001'
    volumes:
      - /home/danieldbird/Dockers/uptime-kuma/app/data:/app/data
    restart: unless-stopped
    image: louislam/uptime-kuma:latest

  diun:
    container_name: diun
    command: serve
    volumes:
      - '/home/danieldbird/Dockers/diun/data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - TZ=Pacific/Auckland
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 0 * * FRI
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_NOTIF_SLACK_WEBHOOKURL=$DIUN_NOTIF_SLACK_WEBHOOKURL
      - DIUN_NOTIF_SLACK_RENDERFIELDS=true
    labels:
      - diun.enable=true
    restart: unless-stopped
    image: crazymax/diun:latest

  home-assistant:
    container_name: home-assistant
    volumes:
      - '/home/danieldbird/Dockers/home-assistant/config:/config'
      - '/etc/localtime:/etc/localtime:ro'
    network_mode: host
    restart: unless-stopped
    image: 'homeassistant/home-assistant:latest'

  esphome:
    container_name: esphome
    volumes:
      - '/home/danieldbird/Dockers/esphome/config:/config'
    network_mode: host
    restart: unless-stopped
    image: esphome/esphome:latest

  # eclipse-mosquitto:
  #   container_name: eclipse-mosquitto
  #   ports:
  #     - '1883:1883'
  #   volumes:
  #     - '/home/danieldbird/Dockers/eclipse-mosquitto/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf'
  #     - '/home/danieldbird/Dockers/eclipse-mosquitto/mosquitto/data:/mosquitto/data'
  #     - '/home/danieldbird/Dockers/eclipse-mosquitto/mosquitto/log:/mosquitto/log'
  #   restart: unless-stopped
  #   image: 'eclipse-mosquitto:latest'

  transmission:
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    ports:
      - '9091:9091'
      - '51413:51413'
      - '51413:51413/udp'
    volumes:
      - '/home/danieldbird/Dockers/transmission/config:/config'
      - '/mnt/nas/Media/Downloads:/downloads'
      - '/mnt/nas/Media/Downloads/Watch:/watch'
    restart: unless-stopped
    image: ghcr.io/linuxserver/transmission:latest

  prowlarr:
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    ports:
      - 9696:9696
    volumes:
      - '/home/danieldbird/Dockers/prowlarr/config:/config'
    restart: unless-stopped
    image: lscr.io/linuxserver/prowlarr:latest

  plex:
    container_name: plex
    environment:
      - TZ=Pacific/Auckland
      - PLEX_CLAIM=$PLEX_CLAIM
    volumes:
      - '/home/danieldbird/Dockers/plex/config:/config'
      - '/home/danieldbird/Dockers/plex/transcode:/transcode'
      - '/mnt/nas/Media:/data'
    network_mode: host
    restart: unless-stopped
    image: plexinc/pms-docker:latest

  radarr:
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - '/home/danieldbird/Dockers/radarr/config:/config'
      - '/mnt/nas/Media/Movies/Adult:/adult'
      - '/mnt/nas/Media/Movies/Kid:/kid'
      - '/mnt/nas/Media/Downloads:/downloads'
    network_mode: host
    restart: unless-stopped
    image: 'ghcr.io/linuxserver/radarr:latest'

  sonarr:
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - '/home/danieldbird/Dockers/sonarr/config:/config'
      - '/mnt/nas/Media/TV Shows/Adult:/adult'
      - '/mnt/nas/Media/TV Shows/Kid:/kid'
      - '/mnt/nas/Media/Downloads:/downloads'
    network_mode: host
    restart: unless-stopped
    image: 'ghcr.io/linuxserver/sonarr:latest'

  # readarr:
  #   container_name: readarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Pacific/Auckland
  #   volumes:
  #     - '/home/danieldbird/Dockers/readarr/config:/config'
  #     - '/mnt/nas/Media/Books:/books'
  #     - '/mnt/nas/Media/Downloads:/downloads'
  #   restart: unless-stopped
  #   image: 'lscr.io/linuxserver/readarr:nightly'

  # calibre:
  #   container_name: calibre
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Pacific/Auckland
  #   ports:
  #     - '8080:8080'
  #     - '8081:8081'
  #   volumes:
  #     - '/home/danieldbird/Dockers/calibre/config:/config'
  #     - '/mnt/nas/Media/Books:/books'
  #   restart: unless-stopped
  #   image: 'ghcr.io/linuxserver/calibre:latest'

  # dahuavto2mqtt:
  #   container_name: dahuavto2mqtt
  #   environment:
  #     - DAHUA_VTO_HOST=$DAHUA_VTO_HOST
  #     - DAHUA_VTO_USERNAME=$DAHUA_VTO_USERNAME
  #     - DAHUA_VTO_PASSWORD=$DAHUA_VTO_PASSWORD
  #     - MQTT_BROKER_HOST=$MQTT_BROKER_HOST
  #     - MQTT_BROKER_PORT=$MQTT_BROKER_PORT
  #     - MQTT_BROKER_TOPIC_PREFIX=DahuaVTO
  #     - MQTT_BROKER_CLIENT_ID=DahuaVTO2MQTT
  #     - DEBUG=True
  #   restart: unless-stopped
  #   image: 'eladbar/dahuavto2mqtt:latest'

minecraft:
  container_name: minecraft
  ports:
    - '25565:25565'
  environment:
    - EULA=TRUE
    - MEMORY=2G
  volumes:
    - '/home/danieldbird/Dockers/minecraft/data:/data'
  restart: unless-stopped
  image: 'itzg/minecraft-server:latest'
