services:
  diun:
    container_name: diun
    command: serve
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - 'TZ=Pacific/Auckland'
      - 'LOG_LEVEL=info'
      - 'LOG_JSON=false'
      - 'DIUN_WATCH_WORKERS=20'
      - 'DIUN_WATCH_SCHEDULE=0 0 * * *'
      - 'DIUN_WATCH_JITTER=30s'
      - 'DIUN_PROVIDERS_DOCKER=true'
      - 'DIUN_NOTIF_SLACK_WEBHOOKURL=$DIUN_NOTIF_SLACK_WEBHOOKURL'
      - 'DIUN_NOTIF_SLACK_RENDERFIELDS=true'
      - 'DIUN_NOTIF_SLACK_TEMPLATEBODY=Camera Server: Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.'
    labels:
      - 'diun.enable=true'
    restart: always
    image: crazymax/diun:latest

  home-assistant:
    container_name: home-assistant
    restart: always
    network_mode: host
    volumes:
      - '/home/danieldbird/Dockers/home-assistant:/config'
      - '/etc/localtime:/etc/localtime:ro'
    image: 'homeassistant/home-assistant:stable'

  plex:
    container_name: plex
    network_mode: host
    restart: always
    environment:
      - TZ=Pacific/Auckland
      - PLEX_CLAIM=<claimToken>
    volumes:
      - '/home/danieldbird/Dockers/plex/config:/config'
      - '/home/danieldbird/Dockers/plex/transcode:/transcode'
      - '/mnt/nas/Media:/data'
    image: plexinc/pms-docker:latest

  transmission:
    container_name: transmission
    restart: always
    ports:
      - '9091:9091'
      - '51413:51413'
      - '51413:51413/udp'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - '/home/danieldbird/Dockers/transmission/config:/config'
      - '/mnt/nas/Media/Downloads:/downloads'
      - '/mnt/nas/Media/Downloads/Watch:/watch'
    image: ghcr.io/linuxserver/transmission:latest

  jackett:
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - '/home/danieldbird/Dockers/jackett/config:/config'
      - '/mnt/nas/Media/Downloads:/downloads'
    network_mode: host
    restart: always
    image: 'ghcr.io/linuxserver/jackett:latest'

  radarr:
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - '/home/danieldbird/Dockers/radarr/config:/config'
      - '/mnt/nas/Media/Movies/Adult:/adult'
      - '/mnt/nas/Media/Movies/Kid:/kid'
      - '/mnt/nas/Media/Downloads:/downloads'
    network_mode: host
    restart: always
    image: 'ghcr.io/linuxserver/radarr:latest'

  sonarr:
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - '/home/danieldbird/Dockers/sonarr/config:/config'
      - '/mnt/nas/Media/TV Shows/Adult:/adult'
      - '/mnt/nas/Media/TV Shows/Kid:/kid'
      - '/mnt/nas/Media/Downloads:/downloads'
    network_mode: host
    restart: always
    image: 'ghcr.io/linuxserver/sonarr:latest'

  esphome:
    container_name: esphome
    restart: always
    network_mode: host
    volumes:
      - '/home/danieldbird/Dockers/esphome/config:/config'
    image: esphome/esphome

  mqtt:
    container_name: mqtt
    restart: always
    ports:
      - '1883:1883'
    volumes:
      - '/home/danieldbird/Dockers/mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf'
      - '/home/danieldbird/Dockers/mqtt/data:/mosquitto/data'
      - '/home/danieldbird/Dockers/mqtt/log:/mosquitto/log'
    image: 'eclipse-mosquitto:latest'

  dahuavto2mqtt:
    container_name: dahuavto2mqtt
    environment:
      - DAHUA_VTO_HOST=$DAHUA_VTO_HOST
      - DAHUA_VTO_USERNAME=$DAHUA_VTO_USERNAME
      - DAHUA_VTO_PASSWORD=$DAHUA_VTO_PASSWORD
      - MQTT_BROKER_HOST=$MQTT_BROKER_HOST
      - MQTT_BROKER_PORT=$MQTT_BROKER_PORT
      - MQTT_BROKER_TOPIC_PREFIX=DahuaVTO
      - MQTT_BROKER_CLIENT_ID=DahuaVTO2MQTT
      - DEBUG=True
    restart: always
    image: 'eladbar/dahuavto2mqtt:latest'

  minecraft:
    container_name: minecraft
    network_mode: host
    ports:
      - '25565:25565'
    environment:
      - EULA=TRUE
      - MEMORY=2G
    restart: always
    volumes:
      - '/home/danieldbird/Dockers/minecraft/data:/data'
    image: 'itzg/minecraft-server:latest'
