services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - 'TZ=Pacific/Auckland'
      - 'LOG_LEVEL=info'
      - 'LOG_JSON=false'
      - 'DIUN_WATCH_WORKERS=20'
      - 'DIUN_WATCH_SCHEDULE=0 0 * * *'
      - 'DIUN_WATCH_JITTER=30s'
      - 'DIUN_PROVIDERS_DOCKER=true'
      - 'DIUN_NOTIF_SLACK_WEBHOOKURL=$DIUN_NOTIF_SLACK_WEBHOOKURL'
      - 'DIUN_NOTIF_SLACK_RENDERFIELDS=true'
      - 'DIUN_NOTIF_SLACK_TEMPLATEBODY=Camera Server: Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.'
    labels:
      - 'diun.enable=true'
    restart: always

  plex:
    container_name: plex
    network_mode: host
    restart: always
    environment:
      - TZ=Pacific/Auckland
      - PLEX_CLAIM=<claimToken>
    volumes:
      - '/home/danieldbird/Dockers/plex/config:/config'
      - '/home/danieldbird/Dockers/plex/transcode:/transcode'
      - '/mnt/nas/Media:/data'
    image: plexinc/pms-docker

  radarr:
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - '/home/danieldbird/Dockers/radarr/config:/config'
      - '/mnt/nas/Media/Movies/Adult:/adult'
      - '/mnt/nas/Media/Movies/Kid:/kid'
      - '/mnt/nas/Media/Downloads:/downloads'
    network_mode: host
    restart: always
    image: 'ghcr.io/linuxserver/radarr:latest'
